#!/usr/bin/uwsgi --ini
# vim: ft=dosini

[uwsgi]
# only valid uWSGI options are tolerated
strict = true

env = app_debug=True
# env = app_smtp=smtps://email@example.net:password@smtp.server.net:465/sender@email.net
env = app_smtp=smtp://localhost/root@localhost
env = app_db=mysql://root:root@127.0.0.1/poleom
# env = app_attachments=./attachments
env = app_secret_key=409810e5b68a00d43eeb225aeed0d013005b798d8a6359805e256d7fa87694de
env = app_title=MacBook Forum

# plugin = python3
python-path = ./
module = poleom.main

# attachmenst are stored relative to curent directory
chdir = ./
check-static = ./poleom/assets

autoload = true

master = true
# workers = 3
# processes = 5
# threads = 5
# ugreen = true
# async = 5
gevent = 10
gevent-monkey-patch = true

# Check python code everything N seconds
python-autoreload = 1
#optimize = 2
#limit-as = 32

http = :8000
need-app = true
vacuum = true
